Numpy

In [2]:
import numpy as np 

arr = np.array([1,2,3,4,5])

result = arr+5
print(result)

[ 6  7  8  9 10]


In [3]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
vector = np.array([10,20,30])

result = matrix +vector

print(result)

[[11 22 33]
 [14 25 36]]


In [4]:
matrix = np.array([[1,2,3],
                   [4,5,6]])
coloumn = np.array([[10],
                    [20]])
result = matrix + coloumn
print(result)

[[11 12 13]
 [24 25 26]]


In [7]:
arr = np.array([1,2,np.nan, 4,np.nan])
print(np.isnan(arr))

replace = np.nan_to_num(arr, nan = 3)
print(replace)

print(np.isnan(replace))

[False False  True False  True]
[1. 2. 3. 4. 3.]
[False False False False False]


In [10]:
remove = arr[~np.isnan(arr)]
print(remove)
print(np.isnan(remove))

[1. 2. 4.]
[False False False]


In [11]:
data = np.array([10,20,np.nan, 40])

mean_value  = np.nanmean(data)
print(mean_value)

23.333333333333332


In [12]:
arr = np.array([1,2,3,4,5])
np.save("my_array.npy", arr)

In [13]:
load_array = np.load("my_array.npy")
print(load_array)

[1 2 3 4 5]


In [15]:
a = np.array([1,2,3,4])
b = np.array([4,5,6])

np.savez("arrays.np", first = a, second = b)

In [18]:
load = np.load("arrays.np.npz")
print(load["first"])
print(load["second"])

[1 2 3 4]
[4 5 6]


In [19]:
arr = np.array([[1,2,3],
                [4,5,6]])

np.savetxt("data.txt", arr, fmt="%d")

In [21]:
load = np.loadtxt("data.txt")
print(load)

[[1. 2. 3.]
 [4. 5. 6.]]


In [35]:
import numpy as np
import math as mat
a = np.array([1,2,3,4])
b = np.sqrt(a)
print(b)



[1.         1.41421356 1.73205081 2.        ]


In [37]:
import numpy as np
arr = np.array([1,4,9,16])

print(np.sqrt(arr))
print(arr**2)

[1. 2. 3. 4.]
[  1  16  81 256]


In [38]:
data = np.array([1,2,3,4])

scaled = (data *3) +2
print(scaled)

[ 5  8 11 14]


In [41]:
a = np.array([[2,4,6,8],
               [8,6,4,2]])

print(np.mean(a)) 
print(np.max(a))
print(np.median(a))
print(np.min(a))
print(np.std(a))


5.0
8
5.0
2
2.23606797749979


In [4]:
import numpy as np
a = np.array([[2,3,4],
              [1,2,3]])

print(np.mean(a, axis = 1))

print(np.mean(a, axis = 0 ))

[3. 2.]
[1.5 2.5 3.5]


Dot Product and Cross Product

In [5]:
a = np.array([1,2,3])
b = np.array([4,5,6])

result = np.dot(a,b)
print(result)

32


In [9]:
a = np.array([[1,2],
             [4,5]])
b = np.array([[9,8],
              [4,5]])

result = np.dot(a,b)
print(result)

[[17 18]
 [56 57]]


In [ ]:
a = np.array([1,0,0])
b = np.array([0,1,0])

cross = np.cross(a,b)
print(cross)

# cross formula
#Cx​ = Ay​Bz​−Az​By​
#Cy=Az​Bx​−Ax​Bz
#Cz​=Ax​By​−Ay​Bx​​


[0 0 1]


Transpose

In [ ]:
matrix = np.array([[1,2,3],
                   [4,5,6]])

print(np.transpose(matrix))
# or
print(matrix.T)

[[1 4]
 [2 5]
 [3 6]]
[[1 4]
 [2 5]
 [3 6]]


In [14]:
x = np.array([[1,2],
              [3,4],
              [5,6]])

new = x.T
print(np.dot(new, x))

[[35 44]
 [44 56]]


Statistical Functions

In [17]:
data = np.array([10,20,30,40])
print(np.var(data))
print(np.std(data))

# concept of variance

# Data: [10, 20, 30, 40]
# Mean = (10+20+30+40)/4 = 25
# Differences from mean = [-15, -5, 5, -15]
# Squared differences = [225, 25, 25, 225]
# Variance = (225+25+25+225)/4 = 125


#standard Deviation concept
#Standard deviation = variance ka square root


125.0
11.180339887498949


In [ ]:
values = np.array([14,20,35,40,50])

print(np.percentile(values, 50))
print(np.percentile(values, 75))
print(np.percentile(values, 100))

# concept of percentiles
# as you see in code , 50% is 35 
# 75% is 40 
# 100% is 50 
# so you can easily understand what is it mean

35.0
40.0
50.0


In [ ]:
arr = np.array([1,2,3,4])
print(np.cumsum(arr))

# concept of cumcum
# as you see in code , 
# logic is that 
# 1+2 = 3
# 3+3 = 6
# 6+4 = 10

[ 1  3  6 10]


Array Comparison 

In [24]:
a = np.array([10,20,30])
b= np.array([15,20,25])

print(a>b)
print(a==b)

[False False  True]
[False  True False]


In [26]:
data = np.array([45,60,50,75,30,90])

passed = data[data>=50]
print(passed)

[60 50 75 90]


In [31]:
a= np.array([1,2,3])
b = np.array([1,2,3])
c = np.array([1,2,4])

print(np.array_equal(a,b))
print(np.array_equal(a,c))

True
False


In [33]:
num = np.array([5,15,25,35])

condition  = (num>10) & (num <30)
print(num[condition])

[15 25]


In [11]:
a = np.array([[1,2,3],[4,5,6]])
condition = a<3
print(a[condition])


[1 2]


Numpy long code

In [73]:
import numpy as np
print("========== NUMPY PRACTICE ==========")

print("1. Creating array")


a = np.array([1,2,3,4,5])
print("1D array : \n ", a )

b = np.array([[1,2,3,4],
              [5,6,7,8]])
print("2D Array :\n ", b)


c = np.array([[[1,2,3],
                 [4,5,6],
                 [7,8,9]]])
print("3D Array : \n", c)


zeros = np.zeros((3,3))
print("zeros : \n", zeros)

ones = np.ones((3,3))
print("Ones : \n", ones)

identity = np.eye(4)
print("Identity Matrix : \n", identity)

random_arr = np.random.rand(3,3)
print("Random Array : \n", random_arr)


print("\n2. Array Attributes")
print("Shape a : ", a.shape)
print("Shape b : ", b.shape)
print("Shape c : ", c.shape)

print("Size a : ", a.size)
print("Size b : ", b.size)
print("Size c : ", c.size)

print("Dimension of a : ", a.ndim)
print("Dimension of b : ", b.ndim)
print("Dimension of c : ", c.ndim)

print("DataType of a : ", a.dtype)
print("DataType of a : ", b.dtype)
print("DataType of a : ", c.dtype)


print("\n3. Indexing & Slicing")

'''we will make a new array to perform indexing and slicing'''

arr = np.array([10,20,30,40,50])
print("First Element : ", arr[0])
print("Last Element : ", arr[-1])
print("Slicing : ",arr[2:4])

'''for 2D array'''
matrix = np.array([[1,2,3],
                    [4,5,6],
                    [7,8,9]])

print("First Row : ",matrix[0])
print("First column : ", matrix[:,0])
print("Element : ", matrix[2,1])


print("\n4. Array Operation")

x = np.array([1,2,3,4])
y = np.array([5,6,7,8])
print("Addition of x and y : ", x+y)
print("Subtraction of x and y : ", x-y)
print("Multiplication of x and y : ", x*y)
print("Division of x and y : ", x/y)


print("\n5. Broadcasting")

arr = np.array([[20,30,40],
                [50,60,70]])
print("Add 10 to all index : ", arr+10)
print("subtract 10 to all index : ", arr-10)
print("multiple 10 to all index : ", arr*10)
print("divide 10 to all index : ", arr/10)



print("\n6. Reshaping & Flattening")

arr = np.arange(1,13)
print("Original : ", arr)

rehshaped = arr.reshape(3,4)
print("Reshaped (3x4): \n", rehshaped)

flattened = rehshaped.flatten()
print("Flattened : ", flattened)


print("\n7. Statistics")

data = np.array([10,20,30,40,50])
print("Mean : ",np.mean(data))
print("Median : ",np.median(data))
print("std dev : ",np.std(data))
print("Min : ",np.min(data))
print("Max : ",np.max(data))


print("\n8. filtering")

data = np.array([5,12,7,9,4,21,30,45,11])
filtered = data[data>10]
print("Values > 10 : ", filtered)


========== NUMPY PRACTICE ==========
1. Creating array
1D array : 
  [1 2 3 4 5]
2D Array :
  [[1 2 3 4]
 [5 6 7 8]]
3D Array : 
 [[[1 2 3]
  [4 5 6]
  [7 8 9]]]
zeros : 
 [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Ones : 
 [[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
Identity Matrix : 
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
Random Array : 
 [[0.48899879 0.24343834 0.62439213]
 [0.46932919 0.81829687 0.84543501]
 [0.87183716 0.77560948 0.84739291]]

2. Array Attributes
Shape a :  (5,)
Shape b :  (2, 4)
Shape c :  (1, 3, 3)
Size a :  5
Size b :  8
Size c :  9
Dimension of a :  1
Dimension of b :  2
Dimension of c :  3
DataType of a :  int64
DataType of a :  int64
DataType of a :  int64

3. Indexing & Slicing
First Element :  10
Last Element :  50
Slicing :  [30 40]
First Row :  [1 2 3]
First column :  [1 4 7]
Element :  8

4. Array Operation
Addition of x and y :  [ 6  8 10 12]
Subtraction of x and y :  [-4 -4 -4 -4]
Multiplication of x and y :  [ 5 12 21 32]
Division of x and 